// Mocks generated by Mockito 5.4.2 from annotations
// in auction_mobile/test/features/auth/data/models/auth_user_model_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'package:auction_mobile/features/data/models/auth_user_model.dart'
    as _i3;
import 'package:auction_mobile/features/domain/entities/auth_user.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeAuthUser_0 extends _i1.SmartFake implements _i2.AuthUser {
  _FakeAuthUser_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [AuthUserModel].
///
/// See the documentation for Mockito's code generation for more information.
class MockAuthUserModel extends _i1.Mock implements _i3.AuthUserModel {
  MockAuthUserModel() {
    _i1.throwOnMissingStub(this);
  }

  @override
  String get uuid => (super.noSuchMethod(
        Invocation.getter(#uuid),
        returnValue: '',
      ) as String);

  @override
  String get email => (super.noSuchMethod(
        Invocation.getter(#email),
        returnValue: '',
      ) as String);

  @override
  String get givenName => (super.noSuchMethod(
        Invocation.getter(#givenName),
        returnValue: '',
      ) as String);

  @override
  String get surname => (super.noSuchMethod(
        Invocation.getter(#surname),
        returnValue: '',
      ) as String);

  @override
  List<Object?> get props => (super.noSuchMethod(
        Invocation.getter(#props),
        returnValue: <Object?>[],
      ) as List<Object?>);

  @override
  Map<String, dynamic> toJson() => (super.noSuchMethod(
        Invocation.method(
          #toJson,
          [],
        ),
        returnValue: <String, dynamic>{},
      ) as Map<String, dynamic>);

  @override
  _i2.AuthUser toEntity() => (super.noSuchMethod(
        Invocation.method(
          #toEntity,
          [],
        ),
        returnValue: _FakeAuthUser_0(
          this,
          Invocation.method(
            #toEntity,
            [],
          ),
        ),
      ) as _i2.AuthUser);
}
